container:
  image: node:10

windows_task:
  windows_container:
    dockerfile: .ci/docker/windows/Dockerfile
    os_version: 2019
  install_script: npm install
  test_script: npm test

lint_task:
  install_script: npm install
  test_script: npm run lint

test_task:
  container:
    matrix:
      image: node:11
      image: node:10
      image: node:8
  install_script: npm install
  test_script: npm test

coverage_task:
  env:
    CODECOV_TOKEN: ENCRYPTED[1cff75bbe021a6c009f2df6ff21061f0056c0312359a88e17ce7c22718d1e73fcbd66a696bc6ce95c74041be15280d7f]
  script:
    - npm install
    - npm test
    - npm run codecov

publish_task:
  only_if: $CIRRUS_BRANCH == 'master'
  depends_on:
    - test_task
    - lint_task
  environment:
    GITHUB_TOKEN: ENCRYPTED[9797fc5164c7a6338c866075e6b0624980718cfbec499c651b1a858b1de1fabf2d2c297005f5df461dc66116b80c2a14]
    NPM_TOKEN: ENCRYPTED[fb4c4d308adf6db29ffc41ec9c779b553ef3910b9222356a9b1dc0e33de3edf34607ecc769918c4ff28726665530da51]
  script:
    - npm install
    - npm run compile
    - npx semantic-release
